Title: Instagram API Haskell Bindings 
Hello: Hello
Login: Log in
LoginURL: Instagram log-in url:
LoginOK: Login successful
LoginCode: Code:
LoginToken: Token:
LoginFail: Login failed
LoginFail_Error: Error:
LoginFail_Reason: Reason:
LoginFail_Description: Description:
RequestFail: Request failed

Subscriptions: Subscriptions
Subscription_None: No Subscription
Subscription_Delete: Delete
Subscription_Tag_Create: Create a Tag Subscription
Subscription_Tag: Tag:
Subscription_Create: Create